/*
 * digitalnewzealandzzzzzzzzzzzzzzzz
 *
 * This file was automatically generated by APIMATIC BETA v2.0 on 06/30/2016
 */

package digitalnewzealandzzzzzzzzzzzzzzzz

/** The base Uri for API calls */
const BASEURI string = "http://api.digitalnz.org"

var Config struct {
    /** Your API Key */
    /** Replace the value of ApiKey with an appropriate value */
    ApiKey string
}
