/*
 * digitalnewzealandzzzzzzzzzzzzzzzz
 *
 * This file was automatically generated by APIMATIC BETA v2.0 on 06/30/2016
 */

package searchrecord


import "digitalnewzealandzzzzzzzzzzzzzzzz/models"

/*
 * Interface for the SEARCHRECORD_IMPL
 */
type SEARCHRECORD interface {
    SearchRecord (*SearchRecordInput) (*models.CollectionSearchRecords, error)
}

/*
 * Factory for the SEARCHRECORD interaface returning SEARCHRECORD_IMPL
 */
func NewSEARCHRECORD() SEARCHRECORD {
    return &SEARCHRECORD_IMPL{}
}